In [ ]:
# This file takes the users stocks within their portfolio and then calculates the log returns

In [1]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import matplotlib.pyplot as plt

In [7]:
n = int(input("Enter the number of stocks in your portfolio: "))
tickers = []
weight = []
for i in range(n):
    stock = input("Enter the stock in your portfolio: ")
    tickers.append(stock)
    wt = int(input("Enter its weightage within your portfolio: "))
    weight.append(wt)

print(tickers)

['AAPL', 'LULU']

In [ ]:
data = pd.DataFrame()
for ticker in tickers:
    data[ticker] = yf.download(stock, start="2015-01-01", auto_adjust=False)['Adj Close']
    
data.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                 AAPL       LULU
Date
2015-01-02  55.340000  55.340000
2015-01-05  55.959999  55.959999
2015-01-06  55.570000  55.570000
2015-01-07  57.650002  57.650002
2015-01-08  59.070000  59.070000

In [28]:
log_returns_of_portfolio = pd.DataFrame()
column_list = data.columns.tolist()
for ticker in column_list:
    log_returns_of_portfolio[ticker] = np.log(data[ticker] / data[ticker].shift(1))

log_returns_of_portfolio.head()

                AAPL      LULU
Date
2015-01-02       NaN       NaN
2015-01-05  0.011141  0.011141
2015-01-06 -0.006994 -0.006994
2015-01-07  0.036747  0.036747
2015-01-08  0.024333  0.024333