In [30]:
# Calculating the log returns of the stocks within the portfolio

In [31]:
import numpy as np 
import pandas as pd 
import yfinance as yf
import matplotlib.pyplot as plt

In [32]:
n = int(input("Enter the number of stocks in your portfolio: "))
tickers = []
weight = []
for i in range(n):
    stock = input("Enter the stock in your portfolio: ")
    tickers.append(stock)
    wt = int(input("Enter its weightage within your portfolio: "))
    weight.append(wt)

print(tickers, weight)

['AAPL', 'LULU'] [70, 30]

In [37]:
data = pd.DataFrame()
for ticker in tickers:
    data[ticker] = yf.download(ticker, start="2015-01-01", auto_adjust=False)['Adj Close']
    
data.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                 AAPL       LULU
Date
2015-01-02  24.171753  55.340000
2015-01-05  23.490805  55.959999
2015-01-06  23.493010  55.570000
2015-01-07  23.822437  57.650002
2015-01-08  24.737740  59.070000

In [38]:
log_returns_of_portfolio = pd.DataFrame()
column_list = data.columns.tolist()
for ticker in column_list:
    log_returns_of_portfolio[ticker] = np.log(data[ticker] / data[ticker].shift(1))

log_returns_of_portfolio.tail()

                AAPL      LULU
Date
2026-09-25  0.015215 -0.003351
2026-09-28 -0.007859 -0.007133
2026-09-29 -0.026956 -0.037584
2026-09-30  0.010930 -0.007044
2026-10-01 -0.008141 -0.003437

In [35]:
# Annualization of the data

In [39]:
annualized_return = pd.DataFrame(index=["Annualized Return"])

for ticker in column_list:
    mean_daily_log_return = log_returns_of_portfolio[ticker].mean()

    annualized_return[ticker] = (
        np.exp(mean_daily_log_return * 252) - 1
    )

print(annualized_return)

                       AAPL   LULU
Annualized Return  0.250003  0.048