In [4]:
# Calculating the log returns of the stocks within the portfolio

In [5]:
import numpy as np
import pandas as pd
import yfinance as yf

In [ ]:
n = int(input("Enter the number of stocks in your portfolio: "))
tickers = []
weight = []

# Logging the stocks within the portfolio of the user; and the weightage each of them carries in the portfolio
# (I can ig optimize this by storing the stock and its weight in a pair)

for i in range(n):
    stock = input("Enter the stock in your portfolio: ")
    tickers.append(stock)
    wt = int(input("Enter its weightage within your portfolio: "))
    weight.append(wt)

print(tickers, weight)

['AAPL', 'NKE', 'LULU'] [80, 10, 10]

In [ ]:
data = pd.DataFrame()

# Used a for loop to fetch all the sources,
# and made it (the comment and the code)
# multi-line to avoid getting flagged by Ruff

for ticker in tickers:
    data[ticker] = yf.download(
        ticker,
        start="2015-01-01",
        auto_adjust=False,
    )["Adj Close"]

data.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                 AAPL        NKE       LULU
Date
2015-01-02  24.171753  40.316376  55.340000
2015-01-05  23.490799  39.667294  55.959999
2015-01-06  23.493015  39.433949  55.570000
2015-01-07  23.822435  40.248516  57.650002
2015-01-08  24.737747  41.177620  59.070000

In [ ]:
log_returns_of_portfolio = pd.DataFrame()
column_list = data.columns.tolist()

# Calculated the Log Return
# Not simple return coz,
# simple return = Single portfolio comparison
# log return = multiple portfolio comparsion

for ticker in column_list:
    log_returns_of_portfolio[ticker] = np.log(data[ticker] / data[ticker].shift(1))

log_returns_of_portfolio.head()

                AAPL       NKE      LULU
Date
2015-01-02       NaN       NaN       NaN
2015-01-05 -0.028576 -0.016231  0.011141
2015-01-06  0.000094 -0.005900 -0.006994
2015-01-07  0.013925  0.020446  0.036747
2015-01-08  0.037703  0.022822  0.024333

In [12]:
# Annualization of the data

In [ ]:
annualized_return = pd.DataFrame(index=["Annualized Return"])

for ticker in column_list:
    mean_daily_log_return = log_returns_of_portfolio[ticker].mean()

    # recently learnt should prefer 252 over 250
    # for number of trading days within a year
    annualized_return[ticker] = np.exp(mean_daily_log_return * 252) - 1

print(annualized_return)

                       AAPL       NKE   LULU
Annualized Return  0.250003 -0.011634  0.048

In [13]:
# calculating standard deviation, variance, covariance and correlation

In [ ]:
# Just now learnt the concept of "VECTORIZATION".
# Thanks to vectorization, we do not require to loop through
# all the stocks in the portfolio and calculate the variance individually,
# but rather can do the task within one single statement

# THEREFORE,

annualized_variance_of_stocks = log_returns_of_portfolio.var() * 252
annualized_standard_deviation_of_stocks = log_returns_of_portfolio.std() * np.sqrt(252)
annualized_covariance_of_stocks = log_returns_of_portfolio.cov() * 252
#     # Correlation is a unitless ratio and thus doesn't require to be multiplied with 250
annualized_correlation_of_stocks = log_returns_of_portfolio.corr()

print(f"Annualized std deviation: {annualized_standard_deviation_of_stocks}\n")
print(f"Annualized variance: {annualized_variance_of_stocks}\n")
print(f"Annualized covariance: {annualized_covariance_of_stocks}\n")
print(f"Annualized correlation: {annualized_correlation_of_stocks}\n")

Annualized std deviation: AAPL    4.554462
NKE     4.992078
LULU    6.522495
dtype: float64

Annualized variance: AAPL    0.082314
NKE     0.098892
LULU    0.168821
dtype: float64

Annualized covariance:           AAPL       NKE      LULU
AAPL  0.082314  0.038588  0.042348
NKE   0.038588  0.098892  0.061472
LULU  0.042348  0.061472  0.168821

Annualized correlation:           AAPL       NKE      LULU
AAPL  1.000000  0.427699  0.359238
NKE   0.427699  1.000000  0.475751
LULU  0.359238  0.475751  1.000000